import json
import asyncio
from typing import Dict, Any, Tuple
from langchain_core.messages import HumanMessage
from langchain_groq import ChatGroq
from langchain_google_genai import ChatGoogleGenerativeAI
import os

from app.models import state
from app.services.tts_service import generate_full_audio_from_text

live_evaluator = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0,
    api_key=os.getenv("GROQ_API_KEY", "dummy_key")
)
fallback_live_evaluator = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0, api_key=os.getenv("GOOGLE_API_KEY", "dummy_key"))

async def generate_live_scores(messages, job_title) -> Tuple[Dict[str, Any] | None, Dict[str, int]]:
    try:
        history_msgs = []
        for m in messages[-3:]:
            m_type = m.get("type") if isinstance(m, dict) else m.type
            m_content = m.get("content") if isinstance(m, dict) else m.content
            if m_type in ("human", "ai"):
                history_msgs.append(f"{m_type}: {m_content}")
                
        history = "\n".join(history_msgs)
        if not history: return None
        
        prompt = f"Evaluate the latest response for a {job_title} role. Output strictly JSON with keys: technical, communication, problem_solving (values 0-100). Transcript:\n{history}"
        
        try:
            res = await asyncio.to_thread(live_evaluator.invoke, [HumanMessage(content=prompt)])
        except Exception as e:
            print(f"Groq Live eval error: {e}. Falling back to Gemini...")
            res = await asyncio.to_thread(fallback_live_evaluator.invoke, [HumanMessage(content=prompt)])
            
        content = res.content
        if "{" in content:
            content = content[content.find("{"):content.rfind("}")+1]
            
        token_usage = res.response_metadata.get("token_usage", {})
        tokens = {
            "prompt_tokens": token_usage.get("prompt_tokens", 0),
            "completion_tokens": token_usage.get("completion_tokens", 0),
            "total_tokens": token_usage.get("total_tokens", 0),
        }
        return json.loads(content), tokens
    except Exception as e:
        print(f"Live eval error: {e}")
        return None, {}

async def generate_warning_audio(text: str, language: str) -> Tuple[str, int]:
    return await generate_full_audio_from_text(text, language)

from app.graph.workflow import graph_app

async def process_agent_stream(session_id: str, graph_input: Dict[str, Any], send_delta_func) -> Tuple[Dict[str, Any], str]:
    """
    Invokes LangGraph natively using ainvoke and simulates streaming text deltas via `send_delta_func`.
    Returns the new state and the final text content generated by the AI.
    """
    config = {"configurable": {"thread_id": session_id}}
    
    # Run the graph
    new_state = await graph_app.ainvoke(input=graph_input, config=config)
    
    final_text = ""
    messages = new_state.get("messages", [])
    if messages:
        last_msg = messages[-1]
        msg_type = last_msg.get("type", "") if isinstance(last_msg, dict) else getattr(last_msg, "type", "")
        if msg_type == "ai":
            content = last_msg.get("content", "") if isinstance(last_msg, dict) else getattr(last_msg, "content", "")
            if isinstance(content, str) and not content.strip().startswith("{") and not content.strip().startswith("```"):
                final_text = content
                # Simulate streaming for the frontend typing effect
                chunk_size = 3
                for i in range(0, len(final_text), chunk_size):
                    await send_delta_func(final_text[i:i+chunk_size])
                    await asyncio.sleep(0.01)
                    
    return new_state, final_text
