import json
import asyncio
from typing import Dict, Any, Tuple
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from langchain_google_genai import ChatGoogleGenerativeAI
import os

from app.models import state
from app.services.tts_service import generate_full_audio_from_text

live_evaluator = ChatOpenAI(
    model="qwen-turbo-latest", 
    temperature=0,
    api_key=os.getenv("DASHSCOPE_API_KEY", "dummy_key"),
    base_url="https://dashscope-intl.aliyuncs.com/compatible-mode/v1"
)
fallback_live_evaluator = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0, api_key=os.getenv("GOOGLE_API_KEY", "dummy_key"))

async def generate_live_scores(messages, job_title):
    try:
        history_msgs = []
        for m in messages[-3:]:
            m_type = m.get("type") if isinstance(m, dict) else m.type
            m_content = m.get("content") if isinstance(m, dict) else m.content
            if m_type in ("human", "ai"):
                history_msgs.append(f"{m_type}: {m_content}")
                
        history = "\n".join(history_msgs)
        if not history: return None
        
        prompt = f"Evaluate the latest response for a {job_title} role. Output strictly JSON with keys: technical, communication, problem_solving (values 0-100). Transcript:\n{history}"
        
        try:
            res = await asyncio.to_thread(live_evaluator.invoke, [HumanMessage(content=prompt)])
        except Exception as e:
            print(f"Qwen Live eval error: {e}. Falling back to Gemini...")
            res = await asyncio.to_thread(fallback_live_evaluator.invoke, [HumanMessage(content=prompt)])
            
        content = res.content
        if "{" in content:
            content = content[content.find("{"):content.rfind("}")+1]
        return json.loads(content)
    except Exception as e:
        print(f"Live eval error: {e}")
        return None

async def generate_warning_audio(text: str, language: str) -> str:
    return await generate_full_audio_from_text(text, language)

async def process_agent_stream(session_id: str, graph_input: Dict[str, Any], send_delta_func) -> Tuple[Dict[str, Any], str]:
    """
    Invokes LangGraph via Aegra client and streams text deltas via `send_delta_func`.
    Returns the new state and the final text content generated by the AI.
    """
    async def token_generator():
        current_text = ""
        async for chunk in state.client.runs.stream(
            thread_id=session_id,
            assistant_id=state.assistant_id,
            input=graph_input,
            stream_mode="messages"
        ):
            event = chunk.event if hasattr(chunk, "event") else chunk.get("event")
            data = chunk.data if hasattr(chunk, "data") else chunk.get("data", [])
            print(f"LangGraph Stream Event: {event}")
                
            if event == "messages/partial":
                for msg in data:
                    msg_type = msg.get("type") if isinstance(msg, dict) else getattr(msg, "type", "")
                    if msg_type == "ai":
                        content = msg.get("content", "") if isinstance(msg, dict) else getattr(msg, "content", "")
                        if isinstance(content, str) and len(content) > len(current_text):
                            delta = content[len(current_text):]
                            current_text = content
                            await send_delta_func(delta)
                            yield delta

    final_text = ""
    async for text_delta in token_generator():
        final_text += text_delta
    
    # Fetch updated state after run completes
    state_resp = await state.client.threads.get_state(session_id)
    return state_resp["values"], final_text
